---
- !ruby/object:Settings
  channel: yourchannel # channel to join goes here
  server: irc.freenode.net # server goes here
  port: 6667 # port to use goes here
  botname: myscoots # bot name to use goes here
